site_name: PhonoLab Docs
site_description: Documentation for the PhonoLab project
site_author: UI-linguistic Team
site_url: ""
use_directory_urls: false


# Repository
repo_name: UI-linguistic/phonolab
repo_url: https://github.com/UI-linguistic/phonolab

# Theme configuration
theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep-purple
      accent: cyan
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue-grey
      accent: teal
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant 
    - navigation.tracking
    - navigation.sections
    - toc.follow
    - search.highlight
    - search.share
    - header.autohide
    - content.code.copy
  navigation_depth: 4

extra_css:
  - stylesheets/extra.css

# Extensions
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - tables

  - toc:
      permalink: true
      toc_depth: '2-4'

plugins:
  - offline
  - search
  - awesome-pages
  - mkdocstrings:
      handlers:
        python:
          selection:
            docstring_style: google
          rendering:
            show_source: true
            show_root_heading: true
            show_root_toc_entry: true
            show_object_full_path: false
            show_category_heading: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            parameter_headings: true

# Navigation
nav:
  - Home: index.md
  - Backend:
    - Overview: backend/overview.md
    - Models: backend/models.md
    - API Reference: backend/api.md
  - Frontend:
    - Overview: frontend/overview.md
  - Development:
    - Setup: development/setup.md
