"""Add lesson card fields to Vowel model

Revision ID: 7e3a103b9feb
Revises: 
Create Date: 2025-04-28 13:17:46.621897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e3a103b9feb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quiz_attempts')
    op.drop_table('lesson_instructions')
    op.drop_table('completed_lessons')
    op.drop_table('user_sessions')
    with op.batch_alter_table('vowels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pronounced', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('common_spellings', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('lips', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('tongue', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('example_words', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('mouth_image_url', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vowels', schema=None) as batch_op:
        batch_op.drop_column('mouth_image_url')
        batch_op.drop_column('example_words')
        batch_op.drop_column('tongue')
        batch_op.drop_column('lips')
        batch_op.drop_column('common_spellings')
        batch_op.drop_column('pronounced')

    op.create_table('user_sessions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('session_id', sa.VARCHAR(), nullable=False),
    sa.Column('started_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    op.create_table('completed_lessons',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('session_id', sa.VARCHAR(), nullable=True),
    sa.Column('lesson_id', sa.INTEGER(), nullable=False),
    sa.Column('completed_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['user_sessions.session_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lesson_instructions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('text', sa.VARCHAR(), nullable=False),
    sa.Column('lesson_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quiz_attempts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('session_id', sa.VARCHAR(), nullable=True),
    sa.Column('quiz_id', sa.INTEGER(), nullable=False),
    sa.Column('score', sa.INTEGER(), nullable=False),
    sa.Column('total', sa.INTEGER(), nullable=False),
    sa.Column('attempted_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['user_sessions.session_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
