name: Backend Tests

on:
  push:
    branches: [ main, dev ]
    paths:
      - 'backend/**'
  pull_request:
    branches: [ main, dev ]
    paths:
      - 'backend/**'

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    strategy:
      matrix:
        python-version: [3.9, 3.12, 3.13]
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov
        pip install -e .
        
    - name: Run tests
      run: |
        # Check if any test files exist
        if find tests -name "test_*.py" | grep -q .; then
          # Tests exist, run pytest with coverage
          pytest --cov=src tests/
        else
          # No test files found, consider this a success
          echo "No test files found. Skipping tests."
          exit 0
        fi

  backend-tests:
    name: Backend Tests
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Tests passed
        run: echo "All tests passed!"
