name: Deploy MkDocs

on:
  push:
    branches:
      - gh-pages

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Install MkDocs and plugins
          pip install mkdocs==1.6.1
          pip install mkdocs-autorefs==1.4.1
          pip install mkdocs-awesome-nav==3.1.1
          pip install mkdocs-awesome-pages-plugin==2.10.1
          pip install mkdocs-get-deps==0.2.0
          pip install mkdocs-material==9.6.12
          pip install mkdocs-material-extensions==1.3.1
          pip install mkdocs-minify-plugin==0.8.0
          pip install mkdocstrings==0.29.1
          pip install mkdocstrings-python==1.16.10

      - name: Install backend package
        run: |
          cd backend
          pip install -e .
          
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi
          
          cd ..
          
          python -c "import sys; print(sys.path)"
          python -c "import pkgutil; print([p[1] for p in pkgutil.iter_modules()])"
          python -c "try: import src; print('src module found'); except ImportError as e: print(f'Error importing src: {e}')"
      
      - name: Configure Git user
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
      
      - name: Deploy documentation
        run: mkdocs gh-deploy --force
